analyzer:
  exclude: [build/**, lib/generated/**, lib/generated_plugin_registrant.dart]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  errors:
    avoid_empty_else: error
    avoid_print: error
    avoid_unnecessary_containers: error
    avoid_web_libraries_in_flutter: error
    no_logic_in_create_state: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    sized_box_for_whitespace: error
    use_full_hex_values_for_flutter_colors: error
    use_key_in_widget_constructors: error
    always_use_package_imports: error
    avoid_dynamic_calls: error
    avoid_relative_lib_imports: error
    empty_statements: error
    control_flow_in_finally: error
    avoid_types_as_parameter_names: error
    avoid_type_to_string: error
    avoid_returning_null_for_future: error
    iterable_contains_unrelated_type: error
    prefer_void_to_null: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    always_declare_return_types: error
    always_put_control_body_on_new_line: error
    always_put_required_named_parameters_first: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    avoid_annotating_with_dynamic: error
    avoid_null_checks_in_equality_operators: error
    avoid_multiple_declarations_per_line: error
    avoid_init_to_null: error
    avoid_function_literals_in_foreach_calls: error
    avoid_field_initializers_in_const_classes: error
    avoid_escaping_inner_quotes: error
    avoid_double_and_int_checks: error
    avoid_classes_with_only_static_members: error
    avoid_catching_errors: error
    avoid_positional_boolean_parameters: error
    avoid_redundant_argument_values: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null: error
    avoid_returning_null_for_void: error
    avoid_returning_this: error
    avoid_setters_without_getters: error
    avoid_shadowing_type_parameters: error
    avoid_single_cascade_in_expression_statements: error
    avoid_types_on_closure_parameters: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    cast_nullable_to_non_nullable: error
    constant_identifier_names: error
    curly_braces_in_flow_control_structures: error
    deprecated_consistency: error
    directives_ordering: error
    do_not_use_environment: error
    empty_catches: error
    empty_constructor_bodies: error
    exhaustive_cases: error
    file_names: error
    flutter_style_todos: error
    implementation_imports: error
    join_return_with_assignment: error
    library_names: error
    library_prefixes: error
    no_leading_underscores_for_library_prefixes: error
    no_leading_underscores_for_local_identifiers: error
    no_runtimeType_toString: error
    non_constant_identifier_names: error
    null_check_on_nullable_type_parameter: error
    noop_primitive_operations: error
    null_closures: error
    one_member_abstracts: error
    only_throw_errors: error
    overridden_fields: error
    package_prefixed_library_names: error
    parameter_assignments: error
    prefer_adjacent_string_concatenation: error
    prefer_asserts_with_message: error
    prefer_asserts_in_initializer_lists: error
    prefer_collection_literals: error
    prefer_conditional_assignment: error
    prefer_constructors_over_static_methods: error
    prefer_contains: error
    prefer_double_quotes: error
    prefer_equal_for_default_values: error
    prefer_expression_function_bodies: error
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    prefer_final_parameters: error
    prefer_for_elements_to_map_fromIterable: error
    prefer_function_declarations_over_variables: error
    prefer_generic_function_type_aliases: error
    prefer_if_elements_to_conditional_expressions: error
    prefer_if_null_operators: error
    prefer_initializing_formals: error
    prefer_inlined_adds: error
    prefer_int_literals: error
    prefer_interpolation_to_compose_strings: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_is_not_operator: error
    prefer_iterable_whereType: error
    prefer_mixin: error
    prefer_null_aware_method_calls: error
    prefer_spread_collections: error
    prefer_typing_uninitialized_variables: error
    provide_deprecation_message: error
    recursive_getters: error
    sized_box_shrink_expand: error
    slash_for_doc_comments: error
    sort_child_properties_last: error
    sort_constructors_first: error
    sort_unnamed_constructors_first: error
    tighten_type_of_initializing_formals: error
    type_init_formals: error
    unawaited_futures: error
    unnecessary_await_in_return: error
    unnecessary_brace_in_string_interps: error
    unnecessary_const: error
    unnecessary_constructor_name: error
    unnecessary_getters_setters: error
    unnecessary_lambdas: error
    unnecessary_late: error
    unnecessary_new: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_checks: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_nullable_for_final_variable_declarations: error
    unnecessary_overrides: error
    unnecessary_parenthesis: error
    unnecessary_string_escapes: error
    unnecessary_string_interpolations: error
    unnecessary_this: error
    use_decorated_box: error
    use_function_type_syntax_for_parameters: error
    use_if_null_to_convert_nulls_to_bools: error
    use_is_even_rather_than_modulo: error
    use_named_constants: error
    use_rethrow_when_possible: error
    use_setters_to_change_properties: error
    use_string_buffers: error
    unnecessary_import: error
    cascade_invocations: error

linter:
  rules:
    - cancel_subscriptions
    - avoid_empty_else
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_relative_lib_imports
    - empty_statements
    - control_flow_in_finally
    - avoid_types_as_parameter_names
    - avoid_type_to_string
    - prefer_void_to_null
    - unnecessary_statements
    - unrelated_type_equality_checks
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_null_checks_in_equality_operators
    - avoid_multiple_declarations_per_line
    - avoid_init_to_null
    - avoid_function_literals_in_foreach_calls
    - avoid_field_initializers_in_const_classes
    - avoid_escaping_inner_quotes
    - avoid_double_and_int_checks
    - avoid_classes_with_only_static_members
    - avoid_catching_errors
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cast_nullable_to_non_nullable
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - implementation_imports
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_runtimeType_toString
    - non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - noop_primitive_operations
    - null_closures
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_with_message
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_double_quotes
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_decorated_box
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - cascade_invocations